version: '3.3'
services:
  gulp:
    build: nodejs/ 
    container_name: gulp
    restart: always
    volumes:
      - ./workspace/:/workspace
    ports:
      - "3000:3000"
  go:
    build: golang/
    container_name: go
    restart: always
    volumes:
      - ./workspace/:/workspace
    ports:
      - "8080:8080"
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    volumes:
      - ./workspace/:/workspace
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - go
    links:
      - go
  portainer:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /opt/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "9000:9000"
