version: '3.3'
services:
  gulp:
    image: fdg11/alpine-3.6-gulp-3.9.1
    container_name: gulp
    restart: always
    volumes:
      - ./nodejs/install.sh:/workspace/install.sh:ro
      - ./workspace/:/workspace
    entrypoint:
      - '/workspace/install.sh'
    ports:
      - "3000:3000"
  go:
    image: fdg11/golang1.9.2-alpine3.6
    container_name: go
    restart: always
    volumes:
      - ./golang/:/go/src/app
      - ./workspace/:/workspace
    entrypoint:
      - '/go/src/app/run.sh'
    ports:
      - "8080:8080"
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    restart: always
    volumes:
      - ./workspace/:/workspace
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - go
      - gulp
  portainer:
      image: portainer/portainer
      container_name: portainer
      restart: always
      volumes:
        - /opt/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9000:9000