version: '3.3'
services:
  go:
    image: fdg11/golang1.9.2-alpine3.6
    container_name: go
    restart: always
    volumes:
      - ./golang/:/go/src/app
      - ./workspace/:/workspace
    entrypoint:
      - '/go/src/app/run.sh'пше
  proxy:
    image: magnaz/nginx-acme:1.12-alpine
    container_name: proxy
    restart: always
    environment:
      - ACCOUNT_CONF_PATH=/etc/nginx/ssl/acme.sh.conf
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/nginx/ssl:rw
      - ./workspace/:/workspace
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - go
  portainer:
      image: portainer/portainer
      container_name: portainer
      restart: always
      volumes:
        - /opt/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock